### ISSUE TITLE
Add images to project

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/shipped#55]
What's your opinion of adding images to cards @zachlatta?

**Comment by zachlatta** [comment]
Sounds like a good idea.

Only hesitation is that it might make it harder to submit projects.
Could we automatically scrape images from ChallengePost/other places?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Awesome idea!

**Comment by zachlatta** [comment]
Would this be something that'd happen in shipped or shipit?

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Maybe a cron job that happens every 3 hours, just like jekyll's page generation.

**Comment by zachlatta** [comment]
Let's move discussion to IRC (#hackedu on Freenode).

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
IDK. What are the pros of scraping on submission?

**Comment by TheThirdOne** [comment]
I don't see images fitting in well in the current layout at all.

**Comment by zachlatta** [comment]
I could see them fitting well directly below the header and above the
description.

-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by MaxWofford** [comment]
Do we want to save the images in the commit, or put them in an image hosting service, with a link-to in the yml?

**Comment by MaxWofford** [comment]
Images would be a plus: http://peek.usertesting.com/result/9829730887196?autoplay=true

**Comment by zachlatta** [comment]
Hmm, I think ideally we'd save them directly into the repo so if the image service ever goes down, we'll still have the files.

What are your thoughts on the best way to implement this? Would need some sort of consistent system.

**Comment by jonleung** [comment]
Do we still want to do this?

**Comment by MaxWofford** [comment]
https://github.com/hackclub/shipped/issues/84#issuecomment-163816473

**Comment by MaxWofford** [comment]
Closing this issue because  shipped is deprecated.
