### ISSUE TITLE
Search / Sort functionality

### ISSUE THREAD

**Issue by TheThirdOne** [hackclub/shipped#67]
As the number of projects increases, it will be harder and harder to find interesting (for a given person) projects.

@MaxWofford mentioned tags for hackathons in #51 

A tag system for hackathons as well as subject matter like ai, compiler, app ... would be very useful.

**Comment by zachlatta** [comment]
👍 I like this idea.

**Comment by jonleung** [comment]
Do we still want to do this?

**Comment by MaxWofford** [comment]
https://github.com/hackclub/shipped/issues/84#issuecomment-163816473

**Comment by MaxWofford** [comment]
Closing this issue because  shipped is deprecated.
