### ISSUE TITLE
Rebuilding shipped without club folders

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/shipped#81]
/cc @zachlatta @jonleung @TheThirdOne  

It seems like we are currently limited by using yaml files as our only datastore. See #67.

Thoughts on rebuilding shipped using pg?

**Comment by MaxWofford** [comment]
In a chat with @zachlatta the idea of storing club data as a tag instead of a folder.

**Comment by jonleung** [comment]
We don't currently actively used shipped. Is it still worth doing this issue or should we close it?

**Comment by MaxWofford** [comment]
https://github.com/hackclub/shipped/issues/84#issuecomment-163816473

**Comment by abdulhannanali** [comment]
anyone still working on [shipped](shipped.hackclub.com) ?

**Comment by zachlatta** [comment]
We haven't officially deprecated it, but we're also no longer actively
adding anything to it.

Are you interested in getting involved? Having someone spice things up
would be fantastic.

On Sun, Jun 26, 2016 at 10:19 AM, Hannan Ali <notifications@github.com>
wrote:

> anyone still working on shipped <http://shipped.hackclub.com> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/shipped/issues/81#issuecomment-228611852>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA8j-M9AGnRvu7LT7DJ8Q-HnpSyEjuGeks5qPrSjgaJpZM4F7JZG>
> .
>



-- 
Zach Latta
https://zachlatta.com <http://zachlatta.com>

**Comment by abdulhannanali** [comment]
@zachlatta Thanks! I would definitely like to work on it. I can redesign the templates and add the features that are previously discussed in the issues. :+1:

**Comment by abdulhannanali** [comment]
I can also make the projects sorting better.  They can be sorted by schools, categories and tags etc. just giving a little bit of better experience. This is one of the idea I have but we can definitely work on how we are going to do revamp this. :smile:

**Comment by abdulhannanali** [comment]
Just saw someone already created an issue for adding sorting feature. That's cool

**Comment by MaxWofford** [comment]
Closing this issue because  shipped is deprecated.

**Comment by ssun098** [comment]
Closing because repo is deprecated
