### ISSUE TITLE
Project cards become columns when scrolling down on mobile 

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/shipped#84]
This was tested on Galaxy Note 3 Chrome.

**Comment by zachlatta** [comment]
Can you attach a screenshot?

**Comment by MaxWofford** [comment]
![recorded](https://cloud.githubusercontent.com/assets/5891442/9824961/3dcae3fe-5885-11e5-999e-02a6249a767e.gif)

**Comment by zachlatta** [comment]
We are so good at web development we created the world's first truly
"dynamic" grid.

On Fri, Sep 11, 2015 at 1:01 PM, Max Wofford <notifications@github.com>
wrote:

> [image: recorded]
> <https://cloud.githubusercontent.com/assets/5891442/9824961/3dcae3fe-5885-11e5-999e-02a6249a767e.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/shipped/issues/84#issuecomment-139648179>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Schrodinger's grid.

On Mon, Sep 21, 2015 at 11:27 AM, Zach Latta <zach@hackedu.us> wrote:

> We are so good at web development we created the world's first truly
> "dynamic" grid.
>
> On Fri, Sep 11, 2015 at 1:01 PM, Max Wofford <notifications@github.com>
> wrote:
>
>> [image: recorded]
>> <https://cloud.githubusercontent.com/assets/5891442/9824961/3dcae3fe-5885-11e5-999e-02a6249a767e.gif>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackedu/shipped/issues/84#issuecomment-139648179>.
>>
>
>
>
> --
> Zach Latta
> hackEDU | zach@hackedu.us
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
We don't currently actively used shipped. Is it still worth doing this issue or should we close it?

**Comment by MaxWofford** [comment]
Shipped is still live and linked to from our website.

![screenshot from 2015-12-10 18 23 07](https://cloud.githubusercontent.com/assets/5891442/11734322/19996cf8-9f6b-11e5-8d3c-585e19de99ad.png)

**Comment by MaxWofford** [comment]
Closing this issue because  shipped is deprecated.
